# Template for SDP
# Board: ESP_01S

esphome:
  name: sdp-simulator
  friendly_name: SDP-SIMULATOR

esp8266:
  board: esp01_1m

logger:

api:
  encryption:
    key: "BANmhZKGWFU2VHul6M0TdSb7xE1rrKNBpA48MDLzbi0="

ota:
  password: "83e1110bdb67b7345321871267daaaf5"

web_server:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

packages:
  extras: !include smart-doorphone/src/packages/extras.yaml
  sdp-simulator: !include smart-doorphone/src/packages/sdp-simulator.yaml
