# Template for SDP
# Board: ESP32-CAM

esphome:
  name: sdp
  friendly_name: SDP

esp32:
  board: esp32dev
  framework:
    type: arduino

logger:

api:
  encryption:
    key: "SROWyEBRs3XJwOTiHwFKoYy7ypwLgZsKY0aJZiZ2ggg="

ota:
  password: "5bbcfd5ff699de5288ed65e4ae78b189"

web_server:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

sensor:
  - platform: internal_temperature
    name: "Internal Temperature"

packages:
  extras: !include smart-doorphone/src/packages/extras.yaml
  sdp: !include smart-doorphone/src/packages/sdp.yaml
